### ISSUE TITLE
About GDGMatlab？

### ISSUE THREAD

**Issue by HaoWangCyy** [vanzantom/GDGMatlab#1]
Do you have relevant documentation for learning?  Can you share it with me?

**Comment by vanzantom** [comment]
Concerning the implementation of DG methods, I would recommend you some slides prepared by Prof. Antonietti who is a leading expert in DG methods.
There are available on her website:
http://www1.mate.polimi.it/~antonietti/PERSONAL_WEBPAGE/Teaching.html 
under academic year  A.Y. 2016-2017.


Specific documentation concerning GDGMatlab is not available yet.

**Comment by HaoWangCyy** [comment]
Thank you for providing a good learning document.
